module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: "#FEF2EF",
          100: "#FDE1D9",
          200: "#FAC2B2",
          300: "#F5A08A",
          400: "#EC7B60",
          500: "#E2553B",
          600: "#C13E27",
          700: "#963118",
          800: "#6B230F",
          900: "#3F1408",
          950: "#210B04",
        },
        sunset: {
          50: "#FEF2EF",
          100: "#FDE1D9",
          200: "#FAC2B2",
          300: "#F5A08A",
          400: "#EC7B60",
          500: "#E2553B",
          600: "#C13E27",
          700: "#963118",
          800: "#6B230F",
          900: "#3F1408",
        },
        sage: {
          50: "#F0F6F9",
          100: "#DCECf3",
          200: "#C9DCEA",
          300: "#A3C5D6",
          400: "#76A9C2",
          500: "#4E8EAE",
          600: "#37728F",
          700: "#275973",
          800: "#1B4258",
          900: "#112B3B",
        },
        slate: {
          50: "var(--sl-50)",
          100: "var(--sl-100)",
          200: "var(--sl-200)",
          300: "var(--sl-300)",
          400: "var(--sl-400)",
          500: "var(--sl-500)",
          600: "var(--sl-600)",
          700: "var(--sl-700)",
          800: "var(--sl-800)",
          900: "var(--sl-900)",
          950: "var(--sl-950)",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        soft: "0 2px 10px -2px rgba(15,23,42,0.08)",
        card: "0 8px 30px -8px rgba(15,23,42,0.12)",
        lifted: "0 20px 40px -12px rgba(15,23,42,0.18)",
      },
      fontFamily: {
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        font_awesome_7_free: [
          "Font Awesome 7 Free",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        font_awesome_5_free: [
          "Font Awesome 5 Free",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        fontawesome: [
          "FontAwesome",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        cairo: [
          "Cairo",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        fredoka: [
          "Fredoka",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
