module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Primary brand identity — Deep Teal (#1C8088).
        // Anchors: Turquoise #41AFAF (400), Deep Teal #1C8088 (600), Deep Sea #15727A (700).
        brand: {
          50: "#ECF7F7",
          100: "#CFEAEB",
          200: "#A6D6D8",
          300: "#6FBFC2",
          400: "#41AFAF",
          500: "#2A9298",
          600: "#1C8088",
          700: "#15727A",
          800: "#115960",
          900: "#0E454A",
          950: "#082E32",
        },
        // Accent / buttons — Coral (#E2654A).
        sunset: {
          50: "#FDF2EF",
          100: "#FAE0D8",
          200: "#F4C2B4",
          300: "#ED9E8A",
          400: "#E87E64",
          500: "#E2654A",
          600: "#C9502F",
          700: "#A53E22",
          800: "#82301B",
          900: "#5E2414",
        },
        // Supporting cool accents — Sky Blue #ADD7EA (200) → Turquoise #41AFAF (500).
        sage: {
          50: "#F1FAFB",
          100: "#DCF1F1",
          200: "#ADD7EA",
          300: "#8FCAD8",
          400: "#63B8BE",
          500: "#41AFAF",
          600: "#339195",
          700: "#287377",
          800: "#1F595D",
          900: "#163E41",
        },
        // Warm Sand (#E4CBA3) — soft backgrounds & cards.
        sand: {
          50: "#FBF7F0",
          100: "#F6EEDF",
          200: "#EFDFC4",
          300: "#E4CBA3",
          400: "#D8B57F",
          500: "#C99E5C",
          600: "#B07F3F",
          700: "#8C6332",
          800: "#674A2A",
          900: "#463320",
        },
        slate: {
          50: "var(--sl-50)",
          100: "var(--sl-100)",
          200: "var(--sl-200)",
          300: "var(--sl-300)",
          400: "var(--sl-400)",
          500: "var(--sl-500)",
          600: "var(--sl-600)",
          700: "var(--sl-700)",
          800: "var(--sl-800)",
          900: "var(--sl-900)",
          950: "var(--sl-950)",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        soft: "0 2px 10px -2px rgba(15,23,42,0.08)",
        card: "0 8px 30px -8px rgba(15,23,42,0.12)",
        lifted: "0 20px 40px -12px rgba(15,23,42,0.18)",
      },
      fontFamily: {
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        font_awesome_7_free: [
          "Font Awesome 7 Free",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        font_awesome_5_free: [
          "Font Awesome 5 Free",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        fontawesome: [
          "FontAwesome",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        cairo: [
          "Cairo",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        fredoka: [
          "Fredoka",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
